### ISSUE TITLE
STAC item, type of image "image/jp2" where it should be tiff

### ISSUE THREAD

**Issue by guydou** [sat-utils/sat-stac-sentinel#3]
Hi guys,

I was fetching records from 2019 to my catalog, and I saw that the type of the images in the assets is "image/jp2" but the file themselves are of type `tiff`

For example this asset, but there are many

```
 "B07": {
      "title": "Band 7",
      "type": "image/jp2",
      "eo:bands": [
        6
      ],
      "href": "https://sentinel-s2-l1c.s3.amazonaws.com/tiles/15/T/WK/2019/1/5/0/B07.TIF"
    }
```

Is it expected?

Guy

**Comment by matthewhanson** [comment]
Thanks for pointing that out @guydou ! I can't believe that wasn't caught before. The files should have extensions of jp2, not TIF.

I've updated the lambda function so that new Items ingested to sat-api.developmentseed.org will be fixed, and I'm kicking off an update script to update the existing records.

thanks again!
